# Generated by Django 4.1.7 on 2023-03-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AddField(
            model_name='signup',
            name='c_password',
            field=models.CharField(default='some', max_length=15),
        ),
        migrations.AddField(
            model_name='signup',
            name='mobile',
            field=models.CharField(default='1234', max_length=12),
        ),
        migrations.AddField(
            model_name='signup',
            name='name',
            field=models.CharField(default='some', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='some', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='some', max_length=12),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(default='some', max_length=15),
        ),
    ]
