# Generated by Django 4.1.7 on 2023-04-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_name_contact_lname_contact_fname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotelcontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='some', max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(default='some', max_length=150)),
            ],
        ),
    ]
