# Generated by Django 4.1.7 on 2023-04-02 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_flight_alter_bookroom_date_checkin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='some', max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='some', max_length=12)),
                ('Date', models.DateField(default=datetime.datetime(2023, 4, 2, 23, 32, 17, 53583), verbose_name='Date')),
                ('economy', models.CharField(choices=[('Ac', 'AC'), ('NAc', 'NON AC')], default='STND', max_length=10)),
                ('Adults', models.CharField(default='some', max_length=12)),
                ('Children', models.CharField(default='some', max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 4, 2, 23, 32, 17, 52584), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='Date_checkin',
            field=models.DateField(default=datetime.datetime(2023, 4, 2, 23, 32, 17, 52584), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='Date_checkout',
            field=models.DateField(default=datetime.datetime(2023, 4, 2, 23, 32, 17, 52584), verbose_name='Date'),
        ),
    ]
