# Generated by Django 4.1.7 on 2023-05-06 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_bookroom_date_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookroom',
            name='Date_checkin',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 14, 36, 53, 959008), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='Date_checkout',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 14, 36, 53, 959993), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 14, 36, 53, 959993), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 14, 36, 53, 959993), verbose_name='Date'),
        ),
    ]
