# Generated by Django 4.1.7 on 2023-05-06 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_bookroom_date_checkin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='some', max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='some', max_length=12)),
                ('Date', models.DateField(default=datetime.datetime(2023, 5, 7, 1, 21, 57, 233326), verbose_name='Date')),
                ('economy', models.CharField(choices=[('BGN', 'Business'), ('FST', 'FIRST')], default='STND', max_length=10)),
                ('Adults', models.CharField(default='some', max_length=12)),
                ('Children', models.CharField(default='some', max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='Date_checkin',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 1, 21, 57, 233326), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='Date_checkout',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 1, 21, 57, 233326), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 1, 21, 57, 233326), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 1, 21, 57, 233326), verbose_name='Date'),
        ),
    ]
